<?php

header('Content-disposition: attachment; filename="jj2launcher_settings.ini";');

$v21 = $_GET['path21'];
$v24 = $_GET['path24'];

?>; Jazz Jackrabbit 2 Launcher - Settings file
; This file was generated by the SGIP
; http://djazz.mine.nu/apps/sgip/

[paths]
v1.23=<?php echo $v21; ?>

v1.24=<?php echo $v24; ?>